# training_data.py

training_data2 = [
    {"query": "hi there", "label": "general"},
    {"query": "good night", "label": "general"},
    {"query": "launch youtube", "label": "open"},
    {"query": "start chrome", "label": "open"},
    {"query": "hey", "label": "general"},
    {"query": "morning greetings", "label": "general"},
    {"query": "open up facebook", "label": "open"},
    {"query": "shut down youtube", "label": "close"},
    {"query": "terminate chrome", "label": "close"},
    {"query": "close down facebook", "label": "close"},
    {"query": "silence the audio", "label": "system"},
    {"query": "what's up?", "label": "general"},
    {"query": "how do you do?", "label": "general"},
    {"query": "turn on sound", "label": "system"},
    {"query": "increase volume", "label": "system"},
    {"query": "decrease volume", "label": "system"},
    {"query": "today's date?", "label": "general"},
    {"query": "current time?", "label": "general"},
    {"query": "who's the US president?", "label": "realtime"},
    {"query": "news update on coronavirus", "label": "realtime"},
    {"query": "create image of a kitten", "label": "generate image"},
    {"query": "draw picture of a puppy", "label": "generate image"},
    {"query": "compose a letter", "label": "content"},
    {"query": "continue the video", "label": "system"},
    {"query": "write a mail", "label": "content"},
    {"query": "look up Python tutorials on Google", "label": "google search"},
    {"query": "search for music clips on YouTube", "label": "youtube search"},
    {"query": "what is the latest technology news", "label": "realtime"},
    {"query": "set reminder for 8 AM", "label": "reminder"},
    {"query": "remind me to contact John", "label": "reminder"},
    {"query": "leave", "label": "exit"},
    {"query": "launch Facebook", "label": "open"},
    {"query": "terminate Facebook", "label": "close"},
    {"query": "start playing music", "label": "play"},
    {"query": "stop playing music", "label": "system"},
    {"query": "pause the clip", "label": "system"},
    {"query": "today's weather?", "label": "realtime"},
    {"query": "make me laugh", "label": "general"},
    {"query": "find pasta recipes", "label": "google search"},
    {"query": "show cooking videos", "label": "youtube search"},
    {"query": "remind me to get milk at 7 PM", "label": "reminder"},
    {"query": "launch Gmail", "label": "open"},
    {"query": "terminate Gmail", "label": "close"},
    {"query": "find vacation spots", "label": "google search"},
    {"query": "create a picture of a sunset", "label": "generate image"},
    {"query": "write a climate change report", "label": "content"},
    {"query": "who won the recent world cup?", "label": "realtime"},
    {"query": "turn off lights", "label": "system"},
    {"query": "start the fan", "label": "system"},
    {"query": "play the newest song", "label": "play"},
    {"query": "tell me about Gandhi", "label": "general"},
    {"query": "what's your name?", "label": "general"},
    {"query": "describe Eiffel Tower", "label": "general"},
    {"query": "find latest tech updates", "label": "google search"},
    {"query": "show me cake baking tutorials", "label": "youtube search"},
    {"query": "set reminder for 3 PM meeting", "label": "reminder"},
    {"query": "write a poem on nature", "label": "content"},
    {"query": "launch settings", "label": "open"},
    {"query": "terminate settings", "label": "close"},
    {"query": "what's the capital of France?", "label": "general"},
    {"query": "tell me an interesting fact", "label": "general"},
    {"query": "open Instagram app", "label": "open"},
    {"query": "shut Instagram app", "label": "close"},
    {"query": "play some blues", "label": "play"},
    {"query": "stop music playback", "label": "system"},
    {"query": "pause that video", "label": "system"},
    {"query": "resume the show", "label": "system"},
    {"query": "tomorrow's weather prediction?", "label": "realtime"},
    {"query": "give me a random fact", "label": "general"},
    {"query": "search for lasagna recipe", "label": "google search"},
    {"query": "show yoga video tutorials", "label": "youtube search"},
    {"query": "remind me to take meds at 8 PM", "label": "reminder"},
    {"query": "open calendar app", "label": "open"},
    {"query": "shut down calendar app", "label": "close"},
    {"query": "search holiday spots", "label": "google search"},
    {"query": "generate ocean picture", "label": "generate image"},
    {"query": "write an essay about environment", "label": "content"},
    {"query": "who won the last tennis match?", "label": "realtime"},
    {"query": "switch off the TV", "label": "system"},
    {"query": "switch on the AC", "label": "system"},
    {"query": "play classical tunes", "label": "play"},
    {"query": "give info about Einstein", "label": "general"},
    {"query": "what's your fave color?", "label": "general"},
    {"query": "describe the Great Wall", "label": "general"}
]
