# additional_training_data.py

training_data4 = [
    {"query": "greetings to you", "label": "general"},
    {"query": "good to see you", "label": "general"},
    {"query": "activate YouTube", "label": "open"},
    {"query": "start browser", "label": "open"},
    {"query": "hi there", "label": "general"},
    {"query": "top of the morning to you", "label": "general"},
    {"query": "access Facebook", "label": "open"},
    {"query": "halt YouTube", "label": "close"},
    {"query": "end Chrome session", "label": "close"},
    {"query": "close Facebook tab", "label": "close"},
    {"query": "lower volume", "label": "system"},
    {"query": "what's the latest?", "label": "general"},
    {"query": "how's everything going?", "label": "general"},
    {"query": "unmute sound", "label": "system"},
    {"query": "increase the volume", "label": "system"},
    {"query": "decrease sound level", "label": "system"},
    {"query": "what's today's date?", "label": "general"},
    {"query": "current time please", "label": "general"},
    {"query": "who's the current US president?", "label": "realtime"},
    {"query": "latest updates on COVID-19", "label": "realtime"},
    {"query": "illustrate a cat", "label": "generate image"},
    {"query": "create an image of a dog", "label": "generate image"},
    {"query": "prepare a letter", "label": "content"},
    {"query": "play the video", "label": "system"},
    {"query": "who is the CEO of Google", "label": "realtime"},
    {"query": "what is the score of the ongoing cricket match", "label": "realtime"},
    {"query": "who is the richest person in the world right now", "label": "realtime"},
    {"query": "what are the current cryptocurrency prices", "label": "realtime"},
    {"query": "who is the Governor of California", "label": "realtime"},
    {"query": "what is the latest update on the Mars mission", "label": "realtime"},
    {"query": "who is the current President of France", "label": "realtime"},
    {"query": "draft an email message", "label": "content"},
    {"query": "search for Python guides on Google", "label": "google search"},
    {"query": "find music videos on YouTube", "label": "youtube search"},
    {"query": "set reminder for 8 o'clock AM", "label": "reminder"},
    {"query": "remind me to call John later", "label": "reminder"},
    {"query": "terminate app", "label": "exit"},
    {"query": "initialize Facebook", "label": "open"},
    {"query": "exit Facebook app", "label": "close"},
    {"query": "play some music", "label": "play"},
    {"query": "stop the music", "label": "system"},
    {"query": "pause playback", "label": "system"},
    {"query": "what's the weather update?", "label": "realtime"},
    {"query": "tell me something funny", "label": "general"},
    {"query": "find a pasta recipe", "label": "google search"},
    {"query": "look up cooking videos", "label": "youtube search"},
    {"query": "remind me to buy milk at 7 PM", "label": "reminder"},
    {"query": "open up Gmail", "label": "open"},
    {"query": "close Gmail app", "label": "close"},
    {"query": "search for holiday ideas", "label": "google search"},
    {"query": "generate a sunset illustration", "label": "generate image"},
    {"query": "write about climate change", "label": "content"},
    {"query": "last soccer world cup winner?", "label": "realtime"},
    {"query": "switch off the lights", "label": "system"},
    {"query": "activate the fan", "label": "system"},
    {"query": "play the latest song", "label": "play"},
    {"query": "tell me about Mahatma Gandhi", "label": "general"},
    {"query": "what's your name again?", "label": "general"},
    {"query": "give details about the Eiffel Tower", "label": "general"},
    {"query": "find the latest tech news", "label": "google search"},
    {"query": "show me baking tutorials", "label": "youtube search"},
    {"query": "set reminder for my 3 PM meeting", "label": "reminder"},
    {"query": "compose a nature poem", "label": "content"},
    {"query": "launch settings app", "label": "open"},
    {"query": "exit settings", "label": "close"},
    {"query": "what's the capital of France?", "label": "general"},
    {"query": "share a fun fact", "label": "general"},
    {"query": "start Instagram", "label": "open"},
    {"query": "shut Instagram", "label": "close"},
    {"query": "play some jazz tunes", "label": "play"},
    {"query": "stop music playback", "label": "system"},
    {"query": "pause the video playback", "label": "system"},
    {"query": "resume video playback", "label": "system"},
    {"query": "tomorrow's weather?", "label": "realtime"},
    {"query": "give me an interesting fact", "label": "general"},
    {"query": "search lasagna recipe", "label": "google search"},
    {"query": "find yoga videos on YouTube", "label": "youtube search"},
    {"query": "remind me to take my pills at 8 PM", "label": "reminder"},
    {"query": "open calendar", "label": "open"},
    {"query": "close the calendar app", "label": "close"},
    {"query": "find holiday destinations", "label": "google search"},
    {"query": "generate an ocean drawing", "label": "generate image"},
    {"query": "write an essay about the environment", "label": "content"},
    {"query": "who won the last tennis match?", "label": "realtime"},
    {"query": "turn off the TV now", "label": "system"},
    {"query": "turn on the air conditioner now", "label": "system"},
    {"query": "play some classical music", "label": "play"},
    {"query": "info on Albert Einstein please", "label": "general"},
    {"query": "what's your favorite color again?", "label": "general"},
    {"query": "describe the Great Wall of China", "label": "general"}
]
