# additional_training_data.py

training_data3 = [
    {"query": "hey there", "label": "general"},
    {"query": "good day", "label": "general"},
    {"query": "initiate YouTube", "label": "open"},
    {"query": "launch browser", "label": "open"},
    {"query": "salutations", "label": "general"},
    {"query": "hello there", "label": "general"},
    {"query": "open up Facebook", "label": "open"},
    {"query": "shut down YouTube", "label": "close"},
    {"query": "close web browser", "label": "close"},
    {"query": "terminate Facebook session", "label": "close"},
    {"query": "quiet the sound", "label": "system"},
    {"query": "what's new?", "label": "general"},
    {"query": "how's life?", "label": "general"},
    {"query": "who is the best-selling author at the moment", "label": "realtime"},
    {"query": "what are the latest movie releases", "label": "realtime"},
    {"query": "who is the lead actor in the new blockbuster film", "label": "realtime"},
    {"query": "what is the weather forecast for tomorrow in New York", "label": "realtime"},
    {"query": "enable sound", "label": "system"},
    {"query": "turn volume up", "label": "system"},
    {"query": "turn volume down", "label": "system"},
    {"query": "date of today?", "label": "general"},
    {"query": "current time now?", "label": "general"},
    {"query": "who leads the US?", "label": "realtime"},
    {"query": "latest news on COVID", "label": "realtime"},
    {"query": "draw a cat illustration", "label": "generate image"},
    {"query": "generate a dog picture", "label": "generate image"},
    {"query": "craft a letter", "label": "content"},
    {"query": "play video again", "label": "system"},
    {"query": "draft an email", "label": "content"},
    {"query": "Google search for Python tutorials", "label": "google search"},
    {"query": "search music on YouTube", "label": "youtube search"},
    {"query": "schedule reminder for 8 AM", "label": "reminder"},
    {"query": "remind me to call John later", "label": "reminder"},
    {"query": "quit the app", "label": "exit"},
    {"query": "launch Facebook", "label": "open"},
    {"query": "close Facebook now", "label": "close"},
    {"query": "begin music", "label": "play"},
    {"query": "halt the music", "label": "system"},
    {"query": "pause the video", "label": "system"},
    {"query": "how's the weather today?", "label": "realtime"},
    {"query": "tell me a funny joke", "label": "general"},
    {"query": "find recipe for pasta", "label": "google search"},
    {"query": "look up cooking tutorials on YouTube", "label": "youtube search"},
    {"query": "remind me to get milk at seven", "label": "reminder"},
    {"query": "open Gmail", "label": "open"},
    {"query": "shut down Gmail", "label": "close"},
    {"query": "search vacation spots", "label": "google search"},
    {"query": "generate sunset drawing", "label": "generate image"},
    {"query": "compose climate change essay", "label": "content"},
    {"query": "who won the latest soccer cup?", "label": "realtime"},
    {"query": "turn off the lights now", "label": "system"},
    {"query": "turn on the fan now", "label": "system"},
    {"query": "play the latest track", "label": "play"},
    {"query": "give information about Gandhi", "label": "general"},
    {"query": "what's your name by the way?", "label": "general"},
    {"query": "describe the Eiffel Tower", "label": "general"},
    {"query": "search the latest tech news", "label": "google search"},
    {"query": "show me how to bake a cake on YouTube", "label": "youtube search"},
    {"query": "set a reminder for 3 PM meeting", "label": "reminder"},
    {"query": "write a poem on nature", "label": "content"},
    {"query": "open settings application", "label": "open"},
    {"query": "terminate settings application", "label": "close"},
    {"query": "what's the capital city of France?", "label": "general"},
    {"query": "tell me an interesting fun fact", "label": "general"},
    {"query": "open Instagram", "label": "open"},
    {"query": "close Instagram application", "label": "close"},
    {"query": "play some blues music", "label": "play"},
    {"query": "stop the music playback", "label": "system"},
    {"query": "pause video playback", "label": "system"},
    {"query": "resume the video playback", "label": "system"},
    {"query": "what's the forecast for tomorrow?", "label": "realtime"},
    {"query": "give me a random fun fact", "label": "general"},
    {"query": "search for lasagna instructions", "label": "google search"},
    {"query": "find yoga tutorial videos", "label": "youtube search"},
    {"query": "remind me to take meds at eight PM", "label": "reminder"},
    {"query": "open my calendar app", "label": "open"},
    {"query": "shut down the calendar app", "label": "close"},
    {"query": "search for holiday destinations", "label": "google search"},
    {"query": "generate a picture of the ocean", "label": "generate image"},
    {"query": "compose an environment essay", "label": "content"},
    {"query": "winner of the recent tennis match?", "label": "realtime"},
    {"query": "turn off the television", "label": "system"},
    {"query": "turn on the air conditioner", "label": "system"},
    {"query": "play some classical tunes", "label": "play"},
    {"query": "tell me about Albert Einstein", "label": "general"},
    {"query": "your favorite color?", "label": "general"},
    {"query": "describe the Great Wall of China", "label": "general"}
]
