# additional_training_data.py

training_data1 = [
    {"query": "howdy", "label": "general"},
    {"query": "good afternoon", "label": "general"},
    {"query": "start YouTube", "label": "open"},
    {"query": "open web browser", "label": "open"},
    {"query": "greetings", "label": "general"},
    {"query": "early morning wishes", "label": "general"},
    {"query": "launch Facebook page", "label": "open"},
    {"query": "close YouTube application", "label": "close"},
    {"query": "exit Chrome", "label": "close"},
    {"query": "shut Facebook page", "label": "close"},
    {"query": "mute audio", "label": "system"},
    {"query": "what's happening?", "label": "general"},
    {"query": "how's everything?", "label": "general"},
    {"query": "restore sound", "label": "system"},
    {"query": "raise the volume", "label": "system"},
    {"query": "reduce the volume", "label": "system"},
    {"query": "what date is it today?", "label": "general"},
    {"query": "tell me the time", "label": "general"},
    {"query": "current president of the USA?", "label": "realtime"},
    {"query": "latest news on COVID-19", "label": "realtime"},
    {"query": "draw a cat picture", "label": "generate image"},
    {"query": "create a dog illustration", "label": "generate image"},
    {"query": "draft a letter", "label": "content"},
    {"query": "play the video again", "label": "system"},
    {"query": "compose an email", "label": "content"},
    {"query": "search Google for Python guides", "label": "google search"},
    {"query": "look up music clips on YouTube", "label": "youtube search"},
    {"query": "schedule a reminder for 8 AM", "label": "reminder"},
    {"query": "remind me to call John", "label": "reminder"},
    {"query": "exit the app", "label": "exit"},
    {"query": "open Facebook application", "label": "open"},
    {"query": "shutdown Facebook app", "label": "close"},
    {"query": "begin music playback", "label": "play"},
    {"query": "halt music playback", "label": "system"},
    {"query": "pause the video clip", "label": "system"},
    {"query": "what's the forecast today?", "label": "realtime"},
    {"query": "tell a joke", "label": "general"},
    {"query": "find pasta cooking instructions", "label": "google search"},
    {"query": "search for cooking tutorials on YouTube", "label": "youtube search"},
    {"query": "remind me to buy milk at 7 PM", "label": "reminder"},
    {"query": "open my Gmail account", "label": "open"},
    {"query": "close my Gmail", "label": "close"},
    {"query": "search for vacation ideas", "label": "google search"},
    {"query": "generate a sunset illustration", "label": "generate image"},
    {"query": "draft an essay on climate change", "label": "content"},
    {"query": "winner of the last soccer world cup?", "label": "realtime"},
    {"query": "turn off the lights", "label": "system"},
    {"query": "switch on the fan", "label": "system"},
    {"query": "play the newest track", "label": "play"},
    {"query": "give details about Mahatma Gandhi", "label": "general"},
    {"query": "can I know your name?", "label": "general"},
    {"query": "give an overview of the Eiffel Tower", "label": "general"},
    {"query": "search for the newest tech news", "label": "google search"},
    {"query": "show how to bake a cake", "label": "youtube search"},
    {"query": "set a reminder for my 3 PM meeting", "label": "reminder"},
    {"query": "write a nature-themed poem", "label": "content"},
    {"query": "open my settings", "label": "open"},
    {"query": "close the settings", "label": "close"},
    {"query": "capital city of France?", "label": "general"},
    {"query": "share an interesting fact", "label": "general"},
    {"query": "launch Instagram", "label": "open"},
    {"query": "close Instagram", "label": "close"},
    {"query": "play some blues music", "label": "play"},
    {"query": "stop playing music", "label": "system"},
    {"query": "pause the video playback", "label": "system"},
    {"query": "resume the video", "label": "system"},
    {"query": "forecast for tomorrow?", "label": "realtime"},
    {"query": "give me a fun fact", "label": "general"},
    {"query": "search for lasagna recipes", "label": "google search"},
    {"query": "find yoga tutorials on YouTube", "label": "youtube search"},
    {"query": "remind me to take my pills at 8 PM", "label": "reminder"},
    {"query": "open calendar", "label": "open"},
    {"query": "close the calendar", "label": "close"},
    {"query": "search for holiday destinations", "label": "google search"},
    {"query": "create an ocean illustration", "label": "generate image"},
    {"query": "write an environment essay", "label": "content"},
    {"query": "who won the last tennis match?", "label": "realtime"},
    {"query": "turn off TV", "label": "system"},
    {"query": "turn on AC", "label": "system"},
    {"query": "play classical music", "label": "play"},
    {"query": "info on Albert Einstein", "label": "general"},
    {"query": "your favorite color?", "label": "general"},
    {"query": "describe the Great Wall", "label": "general"},
    {"query": "who is the winner of the latest Nobel Peace Prize", "label": "realtime"},
    {"query": "what is the status of the ongoing elections", "label": "realtime"},
    {"query": "who is the current CEO of Tesla", "label": "realtime"},
    {"query": "what are the top headlines in today's news", "label": "realtime"},
    {"query": "who is the author of the best-selling book", "label": "realtime"},
    {"query": "what are the latest fashion trends", "label": "realtime"},
    {"query": "who is the latest celebrity to get married", "label": "realtime"},
    {"query": "what is the latest update on the space exploration", "label": "realtime"},
    {"query": "who is the current Prime Minister of the UK", "label": "realtime"},
    {"query": "what are the recent developments in AI technology", "label": "realtime"}
]
