# additional_training_data.py
training_data6 = [
    {"query": "please open YouTube", "label": "open"},
    {"query": "could you start the browser?", "label": "open"},
    {"query": "please say hi", "label": "general"},
    {"query": "top of the morning to you", "label": "general"},
    {"query": "please access Facebook", "label": "open"},
    {"query": "would you mind closing YouTube?", "label": "close"},
    {"query": "please end the Chrome session", "label": "close"},
    {"query": "could you please close the Facebook tab?", "label": "close"},
    {"query": "please lower the volume", "label": "system"},
    {"query": "what's the latest?", "label": "general"},
    {"query": "how's everything going?", "label": "general"},
    {"query": "please unmute the sound", "label": "system"},
    {"query": "who is Elon Musk", "label": "realtime"},
    {"query": "what is the latest news on climate change", "label": "realtime"},
    {"query": "who won the last NBA game", "label": "realtime"},
    {"query": "what is the current stock price of Apple", "label": "realtime"},
    {"query": "could you increase the volume?", "label": "system"},
    {"query": "please decrease the sound level", "label": "system"},
    {"query": "could you tell me today's date?", "label": "general"},
    {"query": "what's the current time, please?", "label": "general"},
    {"query": "who's the current US president?", "label": "realtime"},
    {"query": "please provide the latest updates on COVID-19", "label": "realtime"},
    {"query": "could you draw a cat illustration?", "label": "generate image"},
    {"query": "please create an image of a dog", "label": "generate image"},
    {"query": "would you mind preparing a letter?", "label": "content"},
    {"query": "please play the video again", "label": "system"},
    {"query": "could you draft an email?", "label": "content"},
    {"query": "please search for Python guides on Google", "label": "google search"},
    {"query": "could you find music videos on YouTube?", "label": "youtube search"},
    {"query": "please set a reminder for 8 o'clock AM", "label": "reminder"},
    {"query": "would you remind me to call John later?", "label": "reminder"},
    {"query": "please terminate the app", "label": "exit"},
    {"query": "could you initialize Facebook?", "label": "open"},
    {"query": "please exit Facebook app", "label": "close"},
    {"query": "would you play some music, please?", "label": "play"},
    {"query": "please stop the music", "label": "system"},
    {"query": "could you pause the playback?", "label": "system"},
    {"query": "what's the weather update, please?", "label": "realtime"},
    {"query": "please tell me something funny", "label": "general"},
    {"query": "could you find a pasta recipe?", "label": "google search"},
    {"query": "please look up cooking videos", "label": "youtube search"},
    {"query": "would you remind me to buy milk at 7 PM?", "label": "reminder"},
    {"query": "please open up Gmail", "label": "open"},
    {"query": "could you close Gmail app?", "label": "close"},
    {"query": "please search for holiday ideas", "label": "google search"},
    {"query": "could you generate a sunset illustration?", "label": "generate image"},
    {"query": "would you write about climate change, please?", "label": "content"},
    {"query": "who was the last soccer world cup winner?", "label": "realtime"},
    {"query": "please switch off the lights", "label": "system"},
    {"query": "could you activate the fan?", "label": "system"},
    {"query": "please play the latest song", "label": "play"},
    {"query": "could you tell me about Mahatma Gandhi?", "label": "general"},
    {"query": "what's your name again, please?", "label": "general"},
    {"query": "could you give details about the Eiffel Tower?", "label": "general"},
    {"query": "please find the latest tech news", "label": "google search"},
    {"query": "could you show me baking tutorials?", "label": "youtube search"},
    {"query": "please set a reminder for my 3 PM meeting", "label": "reminder"},
    {"query": "would you compose a nature poem?", "label": "content"},
    {"query": "please launch settings app", "label": "open"},
    {"query": "could you exit settings?", "label": "close"},
    {"query": "what's the capital of France, please?", "label": "general"},
    {"query": "please share a fun fact", "label": "general"},
    {"query": "could you start Instagram?", "label": "open"},
    {"query": "please shut Instagram", "label": "close"},
    {"query": "would you play some jazz tunes, please?", "label": "play"},
    {"query": "please stop music playback", "label": "system"},
    {"query": "could you pause the video playback?", "label": "system"},
    {"query": "please resume video playback", "label": "system"},
    {"query": "what's the forecast for tomorrow, please?", "label": "realtime"},
    {"query": "could you give me an interesting fact?", "label": "general"},
    {"query": "please search lasagna recipe", "label": "google search"},
    {"query": "could you find yoga videos on YouTube?", "label": "youtube search"},
    {"query": "please remind me to take my pills at 8 PM", "label": "reminder"},
    {"query": "could you open the calendar?", "label": "open"},
    {"query": "please close the calendar app", "label": "close"},
    {"query": "would you find holiday destinations, please?", "label": "google search"},
    {"query": "please generate an ocean drawing", "label": "generate image"},
    {"query": "could you write an essay about the environment?", "label": "content"},
    {"query": "who won the last tennis match, please?", "label": "realtime"},
    {"query": "please turn off the TV now", "label": "system"},
    {"query": "could you turn on the air conditioner now?", "label": "system"},
    {"query": "would you play some classical music, please?", "label": "play"},
    {"query": "please give me info on Albert Einstein", "label": "general"},
    {"query": "what's your favorite color again, please?", "label": "general"},
    {"query": "could you describe the Great Wall of China?", "label": "general"},
    {"query": "please make a call to mom", "label": "general"},
    {"query": "could you help me with my homework?", "label": "general"},
    {"query": "please book a taxi", "label": "general"},
    {"query": "could you remind me to buy groceries?", "label": "reminder"},
    {"query": "please check my emails", "label": "general"},
    {"query": "could you set an alarm for 7 AM?", "label": "system"},
    {"query": "please make me a to-do list", "label": "general"},
    {"query": "could you help me find my keys?", "label": "general"},
    {"query": "please turn off the alarm", "label": "system"},
    {"query": "could you tell me today's weather?", "label": "realtime"},
    {"query": "please help me with the laundry", "label": "general"},
    {"query": "could you find my friend's contact number?", "label": "general"}
]
