# training_data.py

training_data = [
    {"query": "hello", "label": "general"},
    {"query": "good evening", "label": "general"},
    {"query": "open youtube", "label": "open"},
    {"query": "open chrome", "label": "open"},
    {"query": "hi", "label": "general"},
    {"query": "good morning", "label": "general"},
    {"query": "open facebook", "label": "open"},
    {"query": "close youtube", "label": "close"},
    {"query": "close chrome", "label": "close"},
    {"query": "close facebook", "label": "close"},
    {"query": "mute", "label": "system"},
    {"query": "how are you?", "label": "general"},
    {"query": "how's it going?", "label": "general"},
    {"query": "unmute", "label": "system"},
    {"query": "volume up", "label": "system"},
    {"query": "volume down", "label": "system"},
    {"query": "what is today's date?", "label": "general"},
    {"query": "what is the time?", "label": "general"},
    {"query": "who is the president of the US?", "label": "realtime"},
    {"query": "tell me news about coronavirus", "label": "realtime"},
    {"query": "generate image of a cat", "label": "generate image"},
    {"query": "generate image of a dog", "label": "generate image"},
    {"query": "write a letter", "label": "content"},
    {"query": "resume video", "label": "system"},
    {"query": "write an email", "label": "content"},
    {"query": "search Google for Python tutorials", "label": "google search"},
    {"query": "search YouTube for music videos", "label": "youtube search"},
    {"query": "set a reminder for 8 AM tomorrow", "label": "reminder"},
    {"query": "remind me to call John", "label": "reminder"},
    {"query": "exit", "label": "exit"},
    {"query": "open Facebook", "label": "open"},
    {"query": "close Facebook", "label": "close"},
    {"query": "play music", "label": "play"},
    {"query": "stop music", "label": "system"},
    {"query": "pause video", "label": "system"},
    {"query": "what's the weather today?", "label": "realtime"},
    {"query": "tell me a joke", "label": "general"},
    {"query": "find a recipe for pasta", "label": "google search"},
    {"query": "show me tutorials on cooking", "label": "youtube search"},
    {"query": "remind me to buy milk at 7 PM", "label": "reminder"},
    {"query": "open Gmail", "label": "open"},
    {"query": "close Gmail", "label": "close"},
    {"query": "search for travel destinations", "label": "google search"},
    {"query": "generate image of a sunset", "label": "generate image"},
    {"query": "write a report on climate change", "label": "content"},
    {"query": "who won the last football world cup?", "label": "realtime"},
    {"query": "turn off the lights", "label": "system"},
    {"query": "turn on the fan", "label": "system"},
    {"query": "play the latest song", "label": "play"},
    {"query": "tell me about Mahatma Gandhi", "label": "general"},
    {"query": "what is your name?", "label": "general"},
    {"query": "describe the Eiffel Tower", "label": "general"},
    {"query": "search for the latest tech news", "label": "google search"},
    {"query": "show me how to bake a cake", "label": "youtube search"},
    {"query": "set a reminder for my meeting at 3 PM", "label": "reminder"},
    {"query": "write a poem about nature", "label": "content"},
    {"query": "open settings", "label": "open"},
    {"query": "close settings", "label": "close"},
    {"query": "what is the capital of France?", "label": "general"},
    {"query": "tell me a fun fact", "label": "general"},
    {"query": "open Instagram", "label": "open"},
    {"query": "close Instagram", "label": "close"},
    {"query": "play some jazz music", "label": "play"},
    {"query": "stop playing music", "label": "system"},
    {"query": "pause the video", "label": "system"},
    {"query": "resume the movie", "label": "system"},
    {"query": "what is the weather forecast for tomorrow?", "label": "realtime"},
    {"query": "tell me a random fact", "label": "general"},
    {"query": "find a lasagna recipe", "label": "google search"},
    {"query": "show me yoga tutorials", "label": "youtube search"},
    {"query": "remind me to take my medicine at 8 PM", "label": "reminder"},
    {"query": "open my calendar", "label": "open"},
    {"query": "close the calendar", "label": "close"},
    {"query": "search for holiday destinations", "label": "google search"},
    {"query": "generate an image of the ocean", "label": "generate image"},
    {"query": "write an essay on the environment", "label": "content"},
    {"query": "who won the last tennis championship?", "label": "realtime"},
    {"query": "turn off the TV", "label": "system"},
    {"query": "turn on the air conditioner", "label": "system"},
    {"query": "play some classical music", "label": "play"},
    {"query": "tell me about Albert Einstein", "label": "general"},
    {"query": "what is your favorite color?", "label": "general"},
    {"query": "describe the Great Wall of China", "label": "general"}
]
